openapi: "3.0.0"
info:
  version: 0.2.0
  title: DraCor API
  contact:
    email: "ffischer@hse.ru"
  termsOfService: "https://dracor.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: https://dracor.org/api
paths:
  /info:
    get:
      summary: API info
      description: >-
        Shows version numbers of the dracor-api app and the underlying
        eXist-db.
      operationId: api-info
      tags: [public]
      responses:
        '200':
          description: Returns JSON object
          content:
            application/json:
              example:
                {
                    "existdb": "4.1.0",
                    "name": "DraCor",
                    "status": "alpha",
                    "version": "0.20.1"
                }

  /metrics:
    get:
      summary: List available corpora and their basic metrics
      description: >-
        This endpoint is deprecated. Please use `/corpora`
        with an appropriate `include` query parameter instead.
      operationId: list-metrics
      deprecated: true
      tags: [public]
      responses:
        '200':
          description: Returns object representing available corpora and their metrics
          content:
            application/json:
              schema:
                type: object
              example:
                {
                  "metrics": [
                    {
                      "corpus": {
                        "name": "rus",
                        "title": "Russian Drama Corpus"
                      },
                      "characters": "1859",
                      "female": "408",
                      "male": "1376",
                      "plays": "102",
                      "sp": "53616",
                      "stage": "24007",
                      "text": "102",
                      "updated": "2018-09-03T23:43:01.786+02:00",
                      "wordcount": {
                        "sp": "972008",
                        "stage": "104111",
                        "text": "1.031876E6"
                      }
                    }
                  ]
                }

  /corpora:
    get:
      summary: List available corpora
      operationId: list-corpora
      tags: [public]
      parameters:
        - name: include
          in: query
          description: Include metrics for each corpus
          required: false
          schema:
            type: string
            enum: [metrics]
      responses:
        '200':
          description: Returns list of available corpora
          content:
            application/json:
              schema:
                type: array
              example:
                [
                  {
                    "name": "ger",
                    "title": "German Drama Corpus",
                    "repository": "https://github.com/dracor-org/gerdracor",
                    "uri": "https://dracor.org/api/corpora/ger",
                    "metrics": {
                      "characters": 10001,
                      "female": 1308,
                      "male": 3953,
                      "plays": 471,
                      "sp": 327696,
                      "stage": 139169,
                      "text": 471,
                      "updated": "2019-01-12T00:55:59.145+01:00",
                      "wordcount": {
                        "sp": 7909927.0,
                        "stage": 880356,
                        "text": 8275863.0
                      }
                    },
                  },
                  {
                    "name": "rus",
                    "title": "Russian Drama Corpus",
                    "repository": "https://github.com/dracor-org/rusdracor",
                    "uri": "https://dracor.org/api/corpora/rus",
                    "metrics": {
                      "characters": 2440,
                      "female": 564,
                      "male": 1789,
                      "plays": 141,
                      "sp": 73485,
                      "stage": 31949,
                      "text": 141,
                      "updated": "2019-01-11T22:48:53.865+01:00",
                      "wordcount": {
                        "sp": 1388515.0,
                        "stage": 140415,
                        "text": 1468669.0
                      }
                    }
                  },
                  {
                    "name": "shake",
                    "title": "Shakespeare Drama Corpus",
                    "repository": "https://github.com/dracor-org/shakedracor",
                    "uri": "https://dracor.org/api/corpora/shake",
                    "metrics": {
                      "characters": 1433,
                      "female": 0,
                      "male": 0,
                      "plays": 37,
                      "sp": 31066,
                      "stage": 10450,
                      "text": 37,
                      "updated": "2019-01-11T22:53:29.419+01:00",
                      "wordcount": {
                        "sp": 876744,
                        "stage": 41230,
                        "text": 908286
                      }
                    }
                  }
                ]
    put:
      summary: Add new corpus
      operationId: put-corpora
      tags: [admin]
      requestBody:
        description: Corpus meta data
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - title
              properties:
                name:
                  type: string
                  description: corpus name
                title:
                  type: string
                  description: corpus title
                repository:
                  type: string
                  description: repository URL
                archive:
                  type: string
                  summary: >-
                    URL of ZIP archive containing TEI files of the corpus
                  description: >
                    The TEI file are expected to be placed in a `tei`
                    subdirectory. Other files will be ignored when loading the
                    archive.
            example: |
              {
                "name": "rus",
                "title": "Russian Drama Corpus",
                "repository": "https://github.com/dracor-org/rusdracor"
              }
      responses:
        '200':
          description: Returns corpus metadata
          content:
            application/json:
              schema:
                type: object
        '409':
          description: Corpus already exists
        '400':
          description: Posted data lacks required properties or is malformed

  /corpora/{corpusname}:
    get:
      summary: List corpus content
      description: >-
        Lists all plays available in the corpus including the id, title,
        author(s) and other meta data.
      operationId: list-corpus-content
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns object representing corpus contents
          content:
            application/json:
              schema:
                type: object
                required:
                  - title
                  - dramas
                properties:
                  title:
                    type: string
                    description: corpus title
                  dramas:
                    type: array
                    description: array of plays
                    items:
                      type: object
        '404':
          description: Corpus not found
    delete:
      summary: Remove corpus from database
      operationId: delete-corpus
      tags: [admin]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Corpus deleted
        '404':
          description: Corpus not found


  /corpora/{corpusname}/metadata:
    get:
      summary: List of metadata for all plays in a corpus
      operationId: corpus-metadata
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a list of metadata for all plays
          content:
            application/json:
              schema:
                type: array
                items: object
            text/csv:
              schema:
                type: string

  /corpora/{corpusname}/metadata.csv:
    get:
      summary: List of metadata for all plays in a corpus
      description: >-
        This endpoint is deprecated. Please use `/corpora/{corpusname}/metadata`
        with an appropriate `Accept` header instead.
      operationId: corpus-metadata-csv
      tags: [public]
      deprecated: true
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a comma separated list of metadata for all plays
          content:
            text/csv:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}:
    get:
      summary: Get metadata and network metrics for a single play
      operationId: play-info
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns an object with play meta data
          content:
            application/json:
              schema:
                type: object

  /corpora/{corpusname}/play/{playname}/tei:
    get:
      summary: Get TEI document of a single play
      operationId: play-tei
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns TEI document
          content:
            application/xml:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}/rdf:
    get:
      summary: Get RDF document for a single play
      operationId: play-rdf
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns RDF document
          content:
            application/xml:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}/networkdata/csv:
    get:
      summary: Get network data of a play as CSV
      operationId: network-csv
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns CSV file
          content:
            text/csv:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}/networkdata/gexf:
    get:
      summary: Get network data of a play as GEXF
      operationId: network-gexf
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns GEXF file
          content:
            application/xml:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}/segmentation:
    get:
      summary: Get a list of segments and characters of a play
      operationId: play-segments-xml
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns XML document
          content:
            application/xml:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}/spoken-text:
    get:
      summary: Get spoken text of a play (excluding stage directions)
      operationId: play-spoken-text
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
        - name: gender
          in: query
          required: false
          schema:
            type: string
            enum: [FEMALE, MALE, UNKNOWN]
      responses:
        '200':
          description: Returns plain text document
          content:
            text/plain:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}/spoken-text-by-character:
    get:
      summary: Get spoken text for each character of a play
      operationId: play-spoken-text-by-character
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns texts per character
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    label:
                      type: string
                    isGroup:
                      type: boolean
                    gender:
                      type: string
                      enum: [FEMALE, MALE, UNKNOWN]
                    text:
                      type: array
                      items:
                        type: string
            text/csv:
              schema:
                type: string

  /corpora/{corpusname}/play/{playname}/stage-directions:
    get:
      summary: Get all stage directions of a play
      operationId: play-stage-directions
      tags: [public]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
        - name: playname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns plain text document
          content:
            text/plain:
              schema:
                type: string

  /sparql:
    get:
      summary: SPARQL endpoint
      description: >-
        Submit SPARQL queries with `query` parameter
      operationId: get-sparql
      tags: [public]
      parameters:
        - name: query
          description: A SPARQL query
          in: query
          required: true
          schema:
            type: string
          example: SELECT * WHERE {?s ?p ?o} LIMIT 10
      responses:
        '200':
          description: Returns SPARQL results document
          content:
            application/sparql-results+xml:
              schema:
                type: string

    post:
      summary: SPARQL endpoint
      description: >-
        Post SPARQL queries
      operationId: post-sparql
      requestBody:
        description: SPARQL query
        content:
          application/sparql-query:
            schema:
              type: string
            example: |
              PREFIX owl: <http://www.w3.org/2002/07/owl#>
              PREFIX dracon: <http://dracor.org/ontology#>
              SELECT ?play
              WHERE {
                ?author owl:sameAs <http://www.wikidata.org/entity/Q310866> .
                ?play dracon:has_author ?author .
              }
              LIMIT 50
      tags: [public]
      responses:
        '200':
          description: Returns SPARQL results document
          content:
            application/sparql-results+xml:
              schema:
                type: string

  /corpora/{corpusname}/load:
    get:
      summary: Load corpus data from its repository
      description: >-
        This requires authorization.
      operationId: load-corpus
      tags: [admin]
      parameters:
        - name: corpusname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a list of created collections and documents
          content:
            application/json:
              schema:
                type: array

  /webhook/github:
    post:
      summary: GitHub Webhook
      description: >-
        Endpoint accepting POST requests from Github (see
        https://developer.github.com/webhooks/). We currently only handle push
        events on the master branch.
      operationId: github-webhook
      tags: [webhook]
      parameters:
        - in: header
          name: User-Agent
          required: true
          schema:
            type: string
            pattern: "GitHub-Hookshot/.*"
        - in: header
          name: X-GitHub-Delivery
          required: true
          schema:
            type: string
          example: "4e16d4dc-1d87-11e9-830d-68e2a0832130"
        - in: header
          name: X-GitHub-Event
          required: true
          schema:
            type: string
            enum: ["push"]
        - in: header
          name: X-Hub-Signature
          required: true
          schema:
            type: string
          example: "sha1=6da21762fada5c1d0205c6e42xxxxxxxxxx357c0"
      requestBody:
        description: >-
          Webhook payload (see https://developer.github.com/webhooks/#payloads)
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: >-
            Webhook delivery has been recieved, a status message is being
            returned.
          content:
            application/json:
              schema:
                type: object
              example: |
                {
                  "message": "Delivery accepted.",
                  "result": "/db/data/dracor/webhook/20190121213010-xxx.xml",
                  "scheduled": true
                }

